# Generated by Django 5.2.4 on 2026-05-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manhwa',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
