# Generated by Django 5.2.4 on 2026-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_manhwa_is_popular_manhwa_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='banner_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
