# Generated by Django 5.2.4 on 2026-05-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterpage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='chapter',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='chapters/pdfs/'),
        ),
        migrations.AddField(
            model_name='chapterpage',
            name='image',
            field=models.ImageField(default=1, upload_to='chapters/pages/'),
            preserve_default=False,
        ),
    ]
